name: run-tests
on: pull_request
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v5.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v5.0.0
        with:
          cmd: test